FROM python:3.12

# Install needed packages
RUN apt-get update && \
    apt-get install -y software-properties-common apt-transport-https curl

# Add script and bash command here for setting up dev


# Command to run the application
CMD ["sleep", "infinity"]



