version: '3.5'

services:
  go-dev:
    restart: always
    command: sleep infinity
    image: dev-go:latest
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "~/.config:/home/dev/.config"
    network_mode: "host"

  python-dev:
    restart: always
    command: sleep infinity
    image: dev-python:latest
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "~/.config:/home/dev/.config"
    network_mode: "host"

  node-dev:
    restart: always
    command: sleep infinity
    image: dev-node:latest
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "~/.config:/home/dev/.config"
    network_mode: "host"