services:
  go-dev:
    restart: always
    image: dev-go:latest
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "config:/home/dev/.config"
    network_mode: "host"

  python-dev:
    restart: always
    command: sleep infinity
    image: dev-python:latest
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "config:/home/dev/.config"
    network_mode: "host"

  node-dev:
    restart: always
    command: sleep infinity
    image: dev-node:latest
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "config:/home/dev/.config"
    network_mode: "host"

  registry:
    image: registry:3
    container_name: registry
    restart: always
    ports:
      - "5000:5000"
    # volumes:
    #   - /opt/registry/data:/var/lib/registry

volumes:
  config: