version: '3.5'

services:
  tabby:
    restart: always
    image: tabbyml/tabby:20240321
    environment:
      - TABBY_DISABLE_USAGE_COLLECTION=1
    command: serve --model DeepseekCoder-6.7B --device cuda
    volumes:
      - "$HOME/.tabby:/data"
    ports:
      - 8080:8080
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  go-dev:
    restart: always
    image: dev-go:20240402
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$HOME/persistent/go:/home/dev/work"
    network_mode: "host"

  python-dev:
    restart: always
    image: dev-python:20240402
    volumes:
      - "$HOME/persistent/python:/home/dev/work"