version: '3.5'

services:
  tabby:
    restart: always
    image: tabbyml/tabby:0.9.1 # https://github.com/TabbyML/tabby releases and drop teh 'v'
    environment:
      - TABBY_DISABLE_USAGE_COLLECTION=1
    command: serve --model DeepseekCoder-6.7B --device cuda
    volumes:
      - "$HOME/.tabby:/data"
    ports:
      - 8080:8080
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  go-dev:
    restart: always
    command: sleep infinity
    image: dev-go:latest
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "~/.config:/home/dev/.config"
    network_mode: "host"

  python-dev:
    restart: always
    command: sleep infinity
    image: dev-python:latest
    ports:
      - 8501:8501

  node-dev:
    restart: always
    command: sleep infinity
    image: dev-node:latest